stages:
  - test
  - push
  - release
  
variables:
  CSPROJ_PATH: 'Memtly.Community/Memtly.Community.csproj'
  BUILD_DOCKERFILE: 'Memtly.Community/Dockerfile'
  BUILD_CONFIGURATION: 'Release'
  BUILD_PLATFORMS: 'linux/arm/v7,linux/arm64/v8,linux/amd64'
  BUILD_BUILDER_NAME: 'memtly-builder'
  BUILD_PARALLEL_COUNT: 1
  DOCKER_DRIVER: overlay2
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/*/'
  GIT_SUBMODULE_STRATEGY: recursive
  
cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

.docker_buildx_gitlab: &docker_buildx_gitlab
  image: docker:29
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use --name $BUILD_BUILDER_NAME --driver docker-container || docker buildx use $BUILD_BUILDER_NAME

.docker_buildx_dockerhub: &docker_buildx_dockerhub
  image: docker:29
  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - docker buildx create --use --name $BUILD_BUILDER_NAME --driver docker-container || docker buildx use $BUILD_BUILDER_NAME

#
#   TEST
#

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    - apt-get install -y nodejs
  script:
    - 'dotnet restore'
    - 'dotnet test'

#
#   PRE-RELEASE
#

push_release:
  <<: *docker_buildx_gitlab
  stage: push
  only:
    - /^(feature\/|release\/).+/
    - /^(prerel|rc|release)-.+/
  script:
    - docker buildx build --tag $CI_REGISTRY_IMAGE:pre_release --platform $BUILD_PLATFORMS --build-arg BUILDKIT_MAX_PARALLELISM=$BUILD_PARALLEL_COUNT --push -f $BUILD_DOCKERFILE .
  needs:
    - test

#
#   RELEASE
#

push_latest:
  <<: *docker_buildx_gitlab
  stage: push
  only:
    - main
    - master
  script:
    - docker buildx build --tag $CI_REGISTRY_IMAGE:latest --platform $BUILD_PLATFORMS --build-arg BUILDKIT_MAX_PARALLELISM=$BUILD_PARALLEL_COUNT --push -f $BUILD_DOCKERFILE .
  needs:
    - test
    
#
#   DOCKERHUB RELEASE
#

push_tag:
  <<: *docker_buildx_gitlab
  stage: push
  only:
    - tags
  script:
    - docker buildx build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:latest --platform $BUILD_PLATFORMS --build-arg BUILDKIT_MAX_PARALLELISM=$BUILD_PARALLEL_COUNT --push -f $BUILD_DOCKERFILE .
  needs:
    - test

push_docker_hub:
  <<: *docker_buildx_dockerhub
  stage: release
  only:
    - tags
  script:
    - docker buildx build --tag $DOCKERHUB_USERNAME/memtly_community:$CI_COMMIT_REF_NAME --tag $DOCKERHUB_USERNAME/memtly_community:latest --tag $DOCKERHUB_USERNAME/memtly:$CI_COMMIT_REF_NAME --tag $DOCKERHUB_USERNAME/memtly:ce --tag $DOCKERHUB_USERNAME/memtly:latest --platform $BUILD_PLATFORMS --build-arg BUILDKIT_MAX_PARALLELISM=$BUILD_PARALLEL_COUNT --push -f $BUILD_DOCKERFILE .
  needs:
    - push_tag