stages:
  - test
  - push
  - release
  
variables:
  BUILD_DOCKERFILE: 'WeddingShare/Dockerfile'
  BUILD_CONFIGURATION: 'Release'
  BUILD_PLATFORMS: 'linux/arm/v7,linux/arm64/v8,linux/amd64'
  BUILD_BUILDER_NAME: 'wedding-share-builder-${CI_JOB_ID}'
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/*/'
  
cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push
  
test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - 'dotnet restore'
    - 'dotnet test'

.docker_buildx_gitlab: &docker_buildx_gitlab
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - apk add --no-cache curl
    - mkdir -p ~/.docker/cli-plugins
    - curl -SL https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use --name $BUILD_BUILDER_NAME --driver docker-container || docker buildx use $BUILD_BUILDER_NAME

.docker_buildx_dockerhub: &docker_buildx_dockerhub
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - apk add --no-cache curl
    - mkdir -p ~/.docker/cli-plugins
    - curl -SL https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - docker buildx create --use --name $BUILD_BUILDER_NAME --driver docker-container || docker buildx use $BUILD_BUILDER_NAME

#
#   PRE-RELEASE
#

push_release:
  <<: *docker_buildx_gitlab
  stage: push
  only:
    - /^(feature\/|release\/).+/
    - /^(prerel|rc|release)-.+/
  script:
    - docker buildx build --tag $CI_REGISTRY_IMAGE:pre_release --platform $BUILD_PLATFORMS --push -f $BUILD_DOCKERFILE .
  needs:
    - test

#
#   RELEASE
#

push_latest:
  <<: *docker_buildx_gitlab
  stage: push
  only:
    - main
    - master
  script:
    - docker buildx build --tag $CI_REGISTRY_IMAGE:latest --platform $BUILD_PLATFORMS --push -f $BUILD_DOCKERFILE .
  needs:
    - test
    
#
#   DOCKERHUB RELEASE
#

push_tag:
  <<: *docker_buildx_gitlab
  stage: push
  only:
    - tags
  script:
    - docker buildx build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --platform $BUILD_PLATFORMS --push -f $BUILD_DOCKERFILE .
  needs:
    - test

push_docker_hub:
  <<: *docker_buildx_dockerhub
  stage: release
  only:
    - tags
  script:
    - docker buildx build --tag $DOCKERHUB_USERNAME/wedding_share:$CI_COMMIT_REF_NAME --tag $DOCKERHUB_USERNAME/wedding_share:latest --platform $BUILD_PLATFORMS --push -f $BUILD_DOCKERFILE .
  needs:
    - push_tag